openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths: {}

components:
  schemas:
    User:
      type: object
      title: User
      required:
        - id
        - name
        - email
        - age
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
          format: email
        age:
          type: integer
